name: injector
description: Dependencies injection package.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  infrastructure:
    path: ../infrastructure
  repositories:
    path: ../repositories
  storage:
    path: ../storage
  store:
    path: ../store

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
