name: mapper
description: Mapper classes
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  domain:
    path: ../domain
  types:
    path: ../types

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
